import torch
from bindsnet.network import Network
from bindsnet.network.nodes import LIFNodes, IFNodes, Input
from bindsnet.network.topology import Connection
from bindsnet.learning import PostPre

"""
============================================================
Generated by SNN Meta-Model Framework (BindsNET Expert Ver.)
Optimization Mode: low_energy
Hardware Target: jetson_nano
============================================================
"""

def create_BindsNetEcoModel():
    # 1. 네트워크 초기화
    network = Network(dt=1.0)
    power_mode = "low_energy"

    # 2. 레이어(Nodes) 정의 및 하드웨어 최적화 적용
    # 입력 레이어
    input_layer = Input(n=784, shape=(784,), sum_input=True)
    network.add_layer(input_layer, name="input_layer")

    prev_layer_name = "input_layer"
    prev_layer_size = 784


    
        current_name = "layer_1"
        
        
        # [Hardware-Aware] 저전력 모드: 연산 부하가 적은 IFNodes(Integrate-and-Fire) 사용
        current_layer = IFNodes(n=256, sum_input=True)
        
        
        network.add_layer(current_layer, name=current_name)

        # 3. 연결(Connection) 정의
        network.add_connection(
            Connection(source=network.layers[prev_layer_name], target=network.layers[current_name], update_rule=PostPre),
            source=prev_layer_name, target=current_name
        )
        prev_layer_name = current_name
    

    
        
        
    

    
        current_name = "layer_3"
        
        
        # [Hardware-Aware] 저전력 모드: 연산 부하가 적은 IFNodes(Integrate-and-Fire) 사용
        current_layer = IFNodes(n=10, sum_input=True)
        
        
        network.add_layer(current_layer, name=current_name)

        # 3. 연결(Connection) 정의
        network.add_connection(
            Connection(source=network.layers[prev_layer_name], target=network.layers[current_name], update_rule=PostPre),
            source=prev_layer_name, target=current_name
        )
        prev_layer_name = current_name
    


    return network

# --- 연구용 시뮬레이션 스크립트 ---
if __name__ == "__main__":
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = create_BindsNetEcoModel()
    
    # BindsNET은 네트워크 내의 모든 텐서를 특정 장치로 이동
    model.to(device)

    
    # [Optimization] 저전력 가동을 위한 메모리 최적화 (BindsNET 텐서 half 변환)
    for p in model.parameters():
        p.data = p.data.half()
    print(">>> [BindsNET] Applied Half-precision (FP16) optimization.")
    

    # 시뮬레이션 입력 생성 (Time, Batch, Features)
    data = torch.randn(100, 1, 784).to(device)
    data = data.half()

    # 시뮬레이션 실행 (Research Mode)
    inputs = {"input_layer": data}
    model.run(inputs=inputs, time=100)

    print(f"----------------------------------------")
    print(f"BindsNET Model 'BindsNetEcoModel' Summary:")
    print(f" - Layers: {list(model.layers.keys())}")
    print(f" - Mode: low_energy")
    print(f" - Device: {device}")
    print(f"----------------------------------------")