import torch
from bindsnet.network import Network
from bindsnet.network.nodes import LIFNodes, IFNodes, Input
from bindsnet.network.topology import Connection
from bindsnet.learning import PostPre

"""
============================================================
Generated by SNN Meta-Model Framework (BindsNET Expert Ver.)
Optimization Mode: normal
Hardware Target: high_performance_gpu
============================================================
"""

def create_BindsNetStandardModel():
    # 1. 네트워크 초기화
    network = Network(dt=1.0)
    power_mode = "normal"

    # 2. 레이어(Nodes) 정의 및 하드웨어 최적화 적용
    # 입력 레이어
    input_layer = Input(n=784, shape=(784,), sum_input=True)
    network.add_layer(input_layer, name="input_layer")

    prev_layer_name = "input_layer"
    prev_layer_size = 784


    
        current_name = "layer_1"
        
        
        # [Standard Mode] 누설 전류를 모사하는 LIFNodes 사용
        current_layer = LIFNodes(n=256, sum_input=True, thresh=-52.0, rest=-65.0)
        
        
        network.add_layer(current_layer, name=current_name)

        # 3. 연결(Connection) 정의
        network.add_connection(
            Connection(source=network.layers[prev_layer_name], target=network.layers[current_name], update_rule=PostPre),
            source=prev_layer_name, target=current_name
        )
        prev_layer_name = current_name
    

    
        
        
    

    
        current_name = "layer_3"
        
        
        # [Standard Mode] 누설 전류를 모사하는 LIFNodes 사용
        current_layer = LIFNodes(n=10, sum_input=True, thresh=-52.0, rest=-65.0)
        
        
        network.add_layer(current_layer, name=current_name)

        # 3. 연결(Connection) 정의
        network.add_connection(
            Connection(source=network.layers[prev_layer_name], target=network.layers[current_name], update_rule=PostPre),
            source=prev_layer_name, target=current_name
        )
        prev_layer_name = current_name
    


    return network

# --- 연구용 시뮬레이션 스크립트 ---
if __name__ == "__main__":
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = create_BindsNetStandardModel()
    
    # BindsNET은 네트워크 내의 모든 텐서를 특정 장치로 이동
    model.to(device)

    

    # 시뮬레이션 입력 생성 (Time, Batch, Features)
    data = torch.randn(100, 1, 784).to(device)
    

    # 시뮬레이션 실행 (Research Mode)
    inputs = {"input_layer": data}
    model.run(inputs=inputs, time=100)

    print(f"----------------------------------------")
    print(f"BindsNET Model 'BindsNetStandardModel' Summary:")
    print(f" - Layers: {list(model.layers.keys())}")
    print(f" - Mode: normal")
    print(f" - Device: {device}")
    print(f"----------------------------------------")