// ============================================================
// [C++/SIMD Backend] Generated by SNN Meta-Model
// Project: CppSimdLowPowerModel | Optimization: low_energy
// LIF/IF dynamics standardized via src/lif_dynamics.py (decay/threshold/reset
// baked in as compile-time constants below, identical numerically to the
// values fed into the Python backends for the same metamodel spec).
//
// Build (MSVC, from a "x64 Native Tools Command Prompt"):
//   cl /O2 /fp:fast /arch:AVX2 /EHsc CppSimdLowPowerModel_CppSIMD.cpp /Fe:CppSimdLowPowerModel.exe
// Build (GCC/Clang):
//   g++ -O3 -march=native -ffast-math CppSimdLowPowerModel_CppSIMD.cpp -o CppSimdLowPowerModel
//
// Inner loops use restrict-qualified raw pointers and branch-free neuron
// updates so the compiler's auto-vectorizer can map them onto SIMD (AVX2)
// instructions without any hand-written intrinsics.
// ============================================================
#include <cstdio>
#include <vector>
#include <random>
#include <chrono>





// LIF/IF layer: decay=1.0000000000, threshold=1.0, reset=0.0 (subtract)
static inline void buf1_neuron_update(float* __restrict v, const float* __restrict I, float* __restrict spk, int n) {
    constexpr float decay = 1.0000000000f;
    constexpr float threshold = 1.0000000000f;
    for (int i = 0; i < n; ++i) {
        v[i] = decay * v[i] + I[i];
        float s = (v[i] >= threshold) ? 1.0f : 0.0f;
        spk[i] = s;
        
        v[i] = v[i] - s * threshold; // soft reset (subtract)
        
    }
}





// LIF/IF layer: decay=1.0000000000, threshold=1.0, reset=0.0 (subtract)
static inline void buf3_neuron_update(float* __restrict v, const float* __restrict I, float* __restrict spk, int n) {
    constexpr float decay = 1.0000000000f;
    constexpr float threshold = 1.0000000000f;
    for (int i = 0; i < n; ++i) {
        v[i] = decay * v[i] + I[i];
        float s = (v[i] >= threshold) ? 1.0f : 0.0f;
        spk[i] = s;
        
        v[i] = v[i] - s * threshold; // soft reset (subtract)
        
    }
}



static inline void linear_forward(const float* __restrict x, float* __restrict y,
                                   const float* __restrict W, const float* __restrict b,
                                   int in_f, int out_f) {
    for (int o = 0; o < out_f; ++o) {
        float acc = b[o];
        const float* w_row = W + (size_t)o * in_f;
        for (int k = 0; k < in_f; ++k) {
            acc += w_row[k] * x[k];
        }
        y[o] = acc;
    }
}

int main() {
    const int TIME_STEPS = 25;
    const int INPUT_FEATURES = 784;

    std::mt19937 rng(42); // 재현성을 위한 고정 시드 (학습이 아닌 성능 측정이 목적)
    std::uniform_real_distribution<float> dist(-0.5f, 0.5f);

    // --- 버퍼 및 가중치 선언 ---
    std::vector<float> x_in(INPUT_FEATURES);


    std::vector<float> W0((size_t)784 * 128);
    std::vector<float> b0(128);
    std::vector<float> buf0(128);



    std::vector<float> v1(128, 0.0f); // 막전위, 타임스텝 간 유지됨
    std::vector<float> buf1(128);



    std::vector<float> W2((size_t)128 * 10);
    std::vector<float> b2(10);
    std::vector<float> buf2(10);



    std::vector<float> v3(10, 0.0f); // 막전위, 타임스텝 간 유지됨
    std::vector<float> buf3(10);



    // --- 가중치 초기화 (임의 초기화: 이 프로젝트의 목적은 학습된 정확도가 아니라
    //     레이턴시 측정이므로 학습 루프는 없음) ---


    for (auto& w : W0) w = dist(rng);
    for (auto& b : b0) b = dist(rng);





    for (auto& w : W2) w = dist(rng);
    for (auto& b : b2) b = dist(rng);





    // --- 입력 데이터 사전 생성 (타이밍 측정 구간 밖에서 생성해 순수 추론 지연시간만 측정) ---
    std::vector<std::vector<float>> inputs(TIME_STEPS, std::vector<float>(INPUT_FEATURES));
    for (auto& row : inputs) {
        for (auto& v : row) v = dist(rng);
    }

    long long total_spikes = 0;

    auto t_start = std::chrono::high_resolution_clock::now();
    for (int t = 0; t < TIME_STEPS; ++t) {
        x_in = inputs[t];


        linear_forward(x_in.data(), buf0.data(), W0.data(), b0.data(), 784, 128);



        buf1_neuron_update(v1.data(), buf0.data(), buf1.data(), 128);



        linear_forward(buf1.data(), buf2.data(), W2.data(), b2.data(), 128, 10);



        buf3_neuron_update(v3.data(), buf2.data(), buf3.data(), 10);


        for (float s : buf3) {
            if (s > 0.5f) total_spikes++;
        }
    }
    auto t_end = std::chrono::high_resolution_clock::now();

    double latency_ms = std::chrono::duration<double, std::milli>(t_end - t_start).count();

    std::printf("\n[CppSIMD] Model '%s' (power_mode=%s)\n", "CppSimdLowPowerModel", "low_energy");
    std::printf(" - Time steps: %d | Output width: %d\n", TIME_STEPS, 10);
    std::printf(" - Total spikes: %lld\n", total_spikes);
    std::printf(" - Latency: %.4f ms total | %.6f ms/step\n", latency_ms, latency_ms / TIME_STEPS);

    return 0;
}