import torch
import torch.nn as nn
import snntorch as snn
from snntorch import surrogate
from snntorch import functional as SF

"""
============================================================
Generated by SNN Meta-Model Framework (snnTorch Expert Ver.)
Project: SnnTorchStandard
Target Hardware: General GPU
Optimization Mode: normal
Generated Date: 2026-02-09
============================================================
"""

class SnnTorchStandard(nn.Module):
    """
    SNN Meta-Model Generated Research Class
    This model supports dynamic hardware-aware optimization.
    """
    def __init__(self):
        super().__init__()
        self.model_name = "SnnTorchStandard"
        self.time_steps = 25
        self.power_mode = "normal"
        
        # 1. 아키텍처 정의 (Research-grade 모듈화)
        self.layers = nn.ModuleList()
        

    
        self.layers.append(nn.Linear(784, 128))
    

    
        
        # [Standard Mode] 정밀한 리키 모델(Leaky) 채택
        self.layers.append(snn.Leaky(beta=0.9, spike_grad=surrogate.fast_sigmoid(), init_hidden=True))
        
    

    
        self.layers.append(nn.Linear(128, 10))
    

    
        
        # [Standard Mode] 정밀한 리키 모델(Leaky) 채택
        self.layers.append(snn.Leaky(beta=0.9, spike_grad=surrogate.fast_sigmoid(), init_hidden=True))
        
    


    def forward(self, x: torch.Tensor):
        """
        Input x shape: (T, Batch, Features)
        """
        # snnTorch의 init_hidden=True는 순방향 연산 시 상태를 자동 관리합니다.
        
        spk_monitoring = [] # 연구용 데이터 수집 (Research Monitoring)
        cur_x = x
        
        
        # 시간축(Time-step) 루프 처리
        for step in range(self.time_steps):
            _x = cur_x[step]
            for i, layer in enumerate(self.layers):
                _x = layer(_x)
            
            spk_monitoring.append(_x)
            
        # 모든 시점의 스파이크 결과 통합
        return torch.stack(spk_monitoring)
        

# --- 실행 및 하드웨어 최적화 스크립트 ---
if __name__ == "__main__":
    # 환경 설정
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f">>> Initializing SnnTorchStandard on {device}...")

    model = SnnTorchStandard().to(device)

    

    # 샘플 데이터 생성 (T, B, F)
    test_input = torch.randn(25, 1, 784).to(device)
    

    # 모델 추론 테스트
    with torch.no_grad():
        output = model(test_input)
    
    # 모델 정보 출력 (논문 데이터용)
    print(f"----------------------------------------")
    print(f"Model Result Summary:")
    print(f" - Output Shape: {output.shape}")
    print(f" - Parameters: {sum(p.numel() for p in model.parameters()):,}")
    print(f" - Mode: normal")
    print(f"----------------------------------------")