import torch
import torch.nn as nn
import snntorch as snn
from snntorch import surrogate
from snntorch import functional as SF
from snntorch import utils

"""
============================================================
[snnTorch Expert Framework] Generated by SNN Meta-Model
Project: SnnTorchLowPowerModel | Optimization: low_energy
Feature: Automated State Reset & Integrated Temporal Dynamics
============================================================
"""

class SnnTorchLowPowerModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.model_name = "SnnTorchLowPowerModel"
        self.time_steps = 25
        self.power_mode = "low_energy"
        
        # 1. 아키텍처 정의 (Sequential 모듈화를 통한 가독성 증대)
        # snn.Leaky/Lapicque의 init_hidden=True를 활용하여 상태 관리를 캡슐화함
        self.layers = nn.ModuleList()
        

    
        self.layers.append(nn.Linear(784, 128))
    

    
        # [Hardware-Aware] LIFNode에서 교체됨: 누설 없는 순수 Integrate-and-Fire (decay=1.0)를 Lapicque로 근사
        self.layers.append(snn.Lapicque(beta=1.0, threshold=1.0, reset_mechanism="subtract", spike_grad=surrogate.fast_sigmoid(), init_hidden=True, output=True))
    

    
        self.layers.append(nn.Linear(128, 10))
    

    
        # [Hardware-Aware] LIFNode에서 교체됨: 누설 없는 순수 Integrate-and-Fire (decay=1.0)를 Lapicque로 근사
        self.layers.append(snn.Lapicque(beta=1.0, threshold=1.0, reset_mechanism="subtract", spike_grad=surrogate.fast_sigmoid(), init_hidden=True, output=True))
    


    def forward(self, x: torch.Tensor):
        """
        Input x shape: (T, Batch, Features)
        """
        # [Expert Tip] 매 forward마다 hidden state를 초기화하여 이전 배치의 잔상이 남지 않도록 함
        utils.reset(self.layers) 
        
        spk_monitoring = [] 
        
        
        # 시간축(Time-step) 루프 처리 및 상태 업데이트
        for step in range(self.time_steps):
            _x = x[step]
            # 각 레이어를 통과하며 스파이크와 막전위(Membrane potential) 관리
            for i, layer in enumerate(self.layers):
                if isinstance(layer, (snn.Leaky, snn.Lapicque)):
                    _x, _mem = layer(_x) # snnTorch 뉴런은 (spk, mem)을 반환함
                else:
                    _x = layer(_x)
            
            spk_monitoring.append(_x)
            
        return torch.stack(spk_monitoring)
        

# --- 실행 및 하드웨어 최적화 스크립트 ---
if __name__ == "__main__":
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = SnnTorchLowPowerModel().to(device)

    
    # [Power Optimization] FP16 연산은 임베디드 GPU 메모리 대역폭을 절약함
    model = model.half()
    

    # (T, B, F) 데이터 생성
    test_input = torch.randn(25, 2, 784).to(device)
    if 'low_energy' == 'low_energy': test_input = test_input.half()

    # 추론 및 성능 측정
    model.eval()
    with torch.no_grad():
        # [Research Feature] snnTorch의 functional 라이브러리를 이용한 손실 계산 준비 가능
        output = model(test_input)
    
    print(f"\n✅ Model Result Summary (low_energy):")
    print(f" - Output Shape: {output.shape} (Time, Batch, Classes)")
    print(f" - Parameters: {sum(p.numel() for p in model.parameters()):,}")