import torch
import torch.nn as nn
from spikingjelly.activation_based import neuron, layer, surrogate, functional, monitor

"""
============================================================
[SpikingJelly Integrated Framework] Generated by SNN Meta-Model
Project: SpikingJellyStandardModel | Optimization Mode: normal
Backend:  | Target Hardware: high_performance_gpu
Technical Note: Combined Monitoring, Low-Power FP16, and CuPy Acceleration
============================================================
"""

class SpikingJellyStandardModel(nn.Module):
    def __init__(self, channels: int = 1):
        super().__init__()
        self.model_name = "SpikingJellyStandardModel"
        self.time_steps = 100
        self.step_mode = 'm'
        
        # 1. 아키텍처 정의 (Hardware-Aware & Step-Mode Optimized)
        self.net = nn.Sequential(

    
            layer.Linear(784, 256),
    

    
            # [Optimization] Surrogate: ATan | Backend: 
            neuron.LIFNode(surrogate_function=surrogate.ATan(), 
                           detach_reset=True, 
                           step_mode='m',
                           backend=''),
    

    
            layer.Linear(256, 10),
    

    
            # [Optimization] Surrogate: ATan | Backend: 
            neuron.LIFNode(surrogate_function=surrogate.ATan(), 
                           detach_reset=True, 
                           step_mode='m',
                           backend=''),
    

        )

        # 2. 분석용 모니터링 도구 (Research Ready - 기존 기능 유지)
        # 모든 뉴런의 스파이크 활동을 기록하여 논문용 데이터 추출 가능
        self.spike_monitor = monitor.OutputMonitor(self.net, neuron.BaseNode)

    def forward(self, x: torch.Tensor):
        """
        Input x shape: (T, N, C, H, W) or (T, N, Features)
        """
        # SNN 상태 초기화 (State Management)
        functional.reset_net(self.net)
        
        # 추론 시 모니터링 제어 (조건부 활성화 가능)
        if not self.training:
            self.spike_monitor.disable() 
        else:
            self.spike_monitor.enable()

        # [Spatial-Temporal Synergy] SpikingJelly 전용 연산 가속
        return self.net(x)

# --- 실행, 최적화 및 프로파일링 스크립트 ---
if __name__ == "__main__":
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = SpikingJellyStandardModel().to(device)

    # 3. [Power-Aware Optimization] 저전력 모드: FP16 변환 (기존 기능 + 가속 포함)
    use_fp16 = True if 'normal' == 'low_energy' and device.type == 'cuda' else False
    if use_fp16:
        model = model.half()
        print(">>> Low Energy Mode: Model converted to Mixed-Precision (FP16)")

    # 4. 샘플 입력 처리 (Batch Size: 2로 연구용 시뮬레이션 최적화)
    sample_input = torch.randn(100, 2, 784).to(device)
    if use_fp16: sample_input = sample_input.half()

    # 5. 성능 측정 (Profiling) - 논문의 실험 파트 데이터용
    start_event = torch.cuda.Event(enable_timing=True)
    end_event = torch.cuda.Event(enable_timing=True)

    start_event.record()
    with torch.cuda.amp.autocast(enabled=use_fp16):
        with torch.no_grad():
            output = model(sample_input)
    end_event.record()
    
    torch.cuda.synchronize()
    
    # 6. 결과 리포트 (Analysis)
    print(f"\n✅ Model 'SpikingJellyStandardModel' Successfully Initialized.")
    print(f"✅ Latency: {start_event.elapsed_time(end_event):.2f} ms")
    print(f"✅ Output Shape: {output.shape}")
    print(f"✅ Total Parameters: {sum(p.numel() for p in model.parameters())}")
    print(f"✅ Spike Monitoring Active: {not model.spike_monitor.is_disabled}")