import torch
import torch.nn as nn
from spikingjelly.activation_based import neuron, layer, surrogate, functional, monitor

"""
============================================================
[SpikingJelly Integrated Framework] Generated by SNN Meta-Model
Project: SpikingJellyLowPowerModel | Optimization Mode: low_energy
Backend: torch | Target Hardware: edge_neuromorphic_processor
Technical Note: Combined Monitoring, Low-Power FP16, and CuPy Acceleration
============================================================
"""

class SpikingJellyLowPowerModel(nn.Module):
    def __init__(self, channels: int = 1):
        super().__init__()
        self.model_name = "SpikingJellyLowPowerModel"
        self.time_steps = 40
        self.step_mode = 'm'
        
        # 1. 아키텍처 정의 (Hardware-Aware & Step-Mode Optimized)
        self.net = nn.Sequential(

    
            layer.Linear(784, 128),
    

    
            # [Hardware-Aware] Low Energy Optimization (Integrate-and-Fire, no leak)
            neuron.IFNode(v_threshold=1.0, v_reset=0.0,
                          surrogate_function=surrogate.Sigmoid(),
                          detach_reset=True,
                          step_mode='m',
                          backend='torch'),
    

    
            layer.Linear(128, 10),
    

    
            # [Hardware-Aware] Low Energy Optimization (Integrate-and-Fire, no leak)
            neuron.IFNode(v_threshold=1.0, v_reset=0.0,
                          surrogate_function=surrogate.Sigmoid(),
                          detach_reset=True,
                          step_mode='m',
                          backend='torch'),
    

        )

        # 2. 분석용 모니터링 도구 (Research Ready - 기존 기능 유지)
        # 모든 뉴런의 스파이크 활동을 기록하여 논문용 데이터 추출 가능
        self.spike_monitor = monitor.OutputMonitor(self.net, neuron.BaseNode)

    def forward(self, x: torch.Tensor):
        """
        Input x shape: (T, N, C, H, W) or (T, N, Features)
        """
        # SNN 상태 초기화 (State Management)
        functional.reset_net(self.net)
        
        # 추론 시 모니터링 제어 (조건부 활성화 가능)
        if not self.training:
            self.spike_monitor.disable() 
        else:
            self.spike_monitor.enable()

        # [Spatial-Temporal Synergy] SpikingJelly 전용 연산 가속
        return self.net(x)

# --- 실행, 최적화 및 프로파일링 스크립트 ---
if __name__ == "__main__":
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = SpikingJellyLowPowerModel().to(device)

    # 3. [Power-Aware Optimization] 저전력 모드: FP16 변환 (기존 기능 + 가속 포함)
    use_fp16 = True if 'low_energy' == 'low_energy' and device.type == 'cuda' else False
    if use_fp16:
        model = model.half()
        print(">>> Low Energy Mode: Model converted to Mixed-Precision (FP16)")

    # 4. 샘플 입력 처리 (Batch Size: 2로 연구용 시뮬레이션 최적화)
    sample_input = torch.randn(40, 2, 784).to(device)
    if use_fp16: sample_input = sample_input.half()

    # 5. 성능 측정 (Profiling) - CPU/GPU 어디서나 동작하도록 device에 따라 타이머를 분기함
    #    (CUDA가 없는 엣지/온디바이스 환경 벤치마크가 이 프로젝트의 핵심 목표이므로,
    #     torch.cuda.Event를 무조건 쓰면 CPU 전용 환경에서 아예 실행되지 않음)
    import time

    if device.type == 'cuda':
        start_event = torch.cuda.Event(enable_timing=True)
        end_event = torch.cuda.Event(enable_timing=True)
        start_event.record()
        with torch.cuda.amp.autocast(enabled=use_fp16):
            with torch.no_grad():
                output = model(sample_input)
        end_event.record()
        torch.cuda.synchronize()
        latency_ms = start_event.elapsed_time(end_event)
    else:
        t_start = time.perf_counter()
        with torch.no_grad():
            output = model(sample_input)
        latency_ms = (time.perf_counter() - t_start) * 1000.0

    # 6. 결과 리포트 (Analysis)
    print(f"\n✅ Model 'SpikingJellyLowPowerModel' Successfully Initialized. (device={device.type})")
    print(f"✅ Latency: {latency_ms:.4f} ms")
    print(f"✅ Output Shape: {output.shape}")
    print(f"✅ Total Parameters: {sum(p.numel() for p in model.parameters())}")