import torch
import torch.nn as nn
from spikingjelly.activation_based import neuron, layer, surrogate, functional, monitor

"""
============================================================
Generated by SNN Meta-Model Framework
Project: StandardModel
Target Hardware: General GPU
Optimization Mode: normal
Generated Date: 2026-02-09
============================================================
"""

class StandardModel(nn.Module):
    def __init__(self, channels: int = 1):
        super().__init__()
        self.model_name = "StandardModel"
        self.time_steps = 50
        
        # 1. 아키텍처 정의 (Encapsulation)
        self.net = nn.Sequential(

    
            layer.Linear(784, 128),
    

    
            neuron.LIFNode(surrogate_function=surrogate.Sigmoid(), detach_reset=True),
    

    
            layer.Linear(128, 10),
    

    
            neuron.LIFNode(surrogate_function=surrogate.Sigmoid(), detach_reset=True),
    

        )

        # 2. 분석용 모니터링 도구 (Research Ready)
        self.spike_monitor = monitor.OutputMonitor(self.net, neuron.BaseNode)

    def forward(self, x: torch.Tensor):
        """
        Input x shape: (T, N, C, H, W) 또는 (T, N, Features)
        """
        # SNN 상태 초기화 (State Management)
        functional.reset_net(self.net)
        self.spike_monitor.disable() # 추론 시에는 모니터링 선택적 비활성화 가능
        
        
        # Multi-step processing (Temporal Dynamics)
        out_list = []
        for t in range(self.time_steps):
            out_list.append(self.net(x[t]))
        return torch.stack(out_list)
        

# --- 실행 및 최적화 스크립트 ---
if __name__ == "__main__":
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = StandardModel().to(device)

    

    # 샘플 입력 (T, Batch, Features)
    sample_input = torch.randn(50, 1, 784).to(device)
    

    # 추론 테스트
    with torch.no_grad():
        output = model(sample_input)
    
    print(f"✅ Model 'StandardModel' Successfully Initialized.")
    print(f"✅ Output Shape: {output.shape}")
    print(f"✅ Total Parameters: {sum(p.numel() for p in model.parameters())}")